version: "3.8"
services:
  # Mysql database container
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD: symfony_password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  # phpmyadmin container
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-OMD-api
    restart: always
    depends_on:
      - db
    ports:
      - 8081:80
    environment:
      PMA_HOST: db
  # Symfony apache project container
  www:
    build: docker/php
    container_name: OMD-api
    ports:
      - 4041:80
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always

networks:
  default:
    external:
      name: OMD-api-network

volumes:
  db-data: