controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

index:
    path: /
    controller: App\Controller\AppController

search:
    path: /search
    controller: App\Controller\AppController